### ISSUE TITLE
The script is only liking business accounts. What can I do to like private accounts?

### ISSUE THREAD

**Issue by passosedu** [GilgameshxZero/ig-liker#1]
My intention is to like all my friends last posts on my timeline. What can I do to solve that?

Thanks in advance, and congrats for the algorithm.

**Comment by GilgameshxZero** [comment]
The script should like whatever is visible on your Instagram feed when you log in.
Do you see posts by your friends when you login to Instagram from a desktop browser?

**Comment by passosedu** [comment]
> The script should like whatever is visible on your Instagram feed when you log in.
> Do you see posts by your friends when you login to Instagram from a desktop browser?

Yeahh.. you're right.. it seems that I had many business account in the moment I tested. Dude, I tested like five times, and I couldn't see a single friend post. But now I do. Thanks a lot!!!! This script is sick!

Let's suppose I'd like to LIKE only private accounts, is this possible? Skipping sponsored posts, Natgeo, Nike, Celebrities, etc? And LIKE exclusively friends. Is there a parameter or statement that I could use?

**Comment by GilgameshxZero** [comment]
I took a short look, but it seems like filtering for only private accounts is not going to be easy. You might be able to get somewhere by compiling a list of the private accounts you want to process, and checking each post that its poster is from that list. But this is going to be more prone to breaking when Instagram updates. Feel free to submit a PR if you do find some way to do what you need.

In the meantime, I've updated the script with more options (documented in the README).

Thank you so much for trying it out! I really appreciate it. Feel free to drop a star if it suits you ^_^
